# Generated by Django 5.1.3 on 2024-12-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listmodel",
            name="is_complete",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
